version: '3.1'

services:
  postgres:
    image: postgres
    container_name: pg-egypto
    restart: always
    environment:
      POSTGRES_USER: "egypto"
      POSTGRES_PASSWORD: "senha"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

networks:
  broker-kafka:
    driver: bridge