CREATE TABLE IF NOT EXISTS AUTORIDADE(
    ID BIGINT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ATIVO BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS PESSOA(
    ID UUID NOT NULL PRIMARY KEY,
    NICKNAME VARCHAR(20) NOT NULL UNIQUE,
    NOME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    AUTORIDADE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ATIVO BOOL NOT NULL,
    FOREIGN KEY (AUTORIDADE_ID) REFERENCES AUTORIDADE(ID)
);

INSERT INTO AUTORIDADE(ID, NOME, CREATED_AT, MODIFIED_AT, ATIVO)
VALUES (1, 'COMUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE);

INSERT INTO AUTORIDADE(ID, NOME, CREATED_AT, MODIFIED_AT, ATIVO)
VALUES (2, 'MODERADOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE);

INSERT INTO AUTORIDADE(ID, NOME, CREATED_AT, MODIFIED_AT, ATIVO)
VALUES (3, 'ADMINISTRADOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE);

INSERT INTO PESSOA(ID, NICKNAME, NOME, EMAIL, SENHA, AUTORIDADE_ID, CREATED_AT, MODIFIED_AT, ATIVO)
VALUES('06db19f9-9457-4c10-aeaa-82cb1186798c', 'admin', 'admin', 'admin@gmail.com', '$2a$12$RrjNL3WnChVSm.17Hmv0N.Bpz1Uv6cLPLnCZO87HKIIrphdiDjwpi', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE);
